[tool.poetry]
name = "alphapi"
version = "0.1.0"
description = ""
authors = ["Nikola Lukic <nkllkc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
alpaca-py = "^0.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
